export const productList = [
  {
    id: 1,
    name: "nike sacai vaporWaffle",
    img: require("@/assets/images/nike-x-sacai-vaporwaffle-royal-fuchsia.jpeg"),
    price: 20000,
    size: "",
  },
  {
    id: 2,
    name: "nike air force 1 low",
    img: require("@/assets/images/air-force-1-07.jpeg"),
    price: 3400,
    size: "",
  },
  {
    id: 3,
    name: "nike air max 97 essential",
    img: require("@/assets/images/air-max-97-essential.jpeg"),
    price: 5400,
    size: "",
  },
  {
    id: 4,
    name: "nike air max 95 essential",
    img: require("@/assets/images/air-max-95-essential.jpeg"),
    price: 5400,
    size: "",
  },
  {
    id: 5,
    name: "adidas yeezy 350v2 black red",
    img: require("@/assets/images/adidas-yeezy-350v2-black-red.jpeg"),
    price: 13000,
    size: "",
  },
  {
    id: 6,
    name: "adidas yeezy 700 og",
    img: require("@/assets/images/adidas-yeezy-700-og.jpeg"),
    price: 14000,
    size: "",
  },
  {
    id: 7,
    name: "adidas yeezy 500 salt",
    img: require("@/assets/images/adidas-originals-yeezy-500-salt.jpeg"),
    price: 9600,
    size: "",
  },
  {
    id: 8,
    name: "new balance 990",
    img: require("@/assets/images/new-balance-990.jpeg"),
    price: 8000,
    size: "",
  },
];
